# -*- coding: utf-8 -*-
"""fando.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18HpWkDfm-fr1w_vi4bXHURFNgIEHSVp2
"""

!pip install pandas-ta yfinance scikit-learn requests
import yfinance as yf
import pandas_ta as ta
import requests
from sklearn.ensemble import RandomForestClassifier

# --- CONFIGURATION ---
TOKEN = "8705574670:AAEQDre27EDsV_4lSW2Z4XBZeBKdfA2Cf34"
CHAT_ID = "6643306745"
SYMBOL = "^NSEI"  # Nifty 50 Index

def send_signal(message):
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={CHAT_ID}&text={message}"
    requests.get(url)

# 1. GET DATA
data = yf.download(SYMBOL, period="1mo", interval="5m")

# 2. FEATURE ENGINEERING (Teaching the AI)
data['RSI'] = ta.rsi(data['Close'], length=14)
data['EMA'] = ta.ema(data['Close'], length=20)
data['Target'] = (data['Close'].shift(-1) > data['Close']).astype(int)
data.dropna(inplace=True)

# 3. TRAIN THE AI AGENT
X = data[['RSI', 'EMA']]
y = data['Target']
model = RandomForestClassifier(n_estimators=100)
model.fit(X[:-1], y[:-1]) # Train on everything except the last candle

# 4. GENERATE SIGNAL
last_row = X.tail(1)
prediction = model.predict(last_row)[0]

if prediction == 1:
    send_signal("🚀 AI SIGNAL: BUY CALL / LONG Nifty")
else:
    send_signal("📉 AI SIGNAL: BUY PUT / SHORT Nifty")